pipeline { 
    agent any  
    stages { 
        stage('SCM Checkout') { 
            steps { 
               echo 'This is a minimal pipeline.' 
               git 'https://github.com/JohannesSchwegler/mavenTest'
            }
        }
    }
}
